### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by ChristopherSkarsethstuen** [Lundix-IT/spcbridge#7]
Error message when trying to add integration
Error - Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

![image](https://github.com/user-attachments/assets/86986a71-3e2e-4d21-8bdd-6666630fcebc)

[log.txt](https://github.com/user-attachments/files/18036571/log.txt)

Core
2024.12.0
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.4

**Comment by jschlyter** [comment]
I've lowered the `pyspcbridge`  requirements to align with Home Assistant 2024.10 and later, please try again and see if it works better now.

**Comment by ChristopherSkarsethstuen** [comment]
Thank you @jschlyter 
I was able to add the integration now
